theme: jekyll-theme-minimal
logo: "/ADITYA_VINAYAK.jpeg"


title: "Aditya Vinayak"
description: >
  <br>
  3rd Year Undergraduate | GLBITM , DR. APJ ABDUL KALAM UNIVERSITY
  <br>
<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="adityavinayak" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://in.linkedin.com/in/adityavinayak?trk=profile-badge">ADITYA VINAYAK</a></div>
              


description: "Hello World, I'm a Developer."
