theme: jekyll-theme-minimal
logo: "/ADITYA_VINAYAK.jpeg"


title: "Aditya Vinayak"
description: >
  <br>
  3rd Year Undergraduate | GLBITM , DR. APJ ABDUL KALAM UNIVERSITY
  <br>
              


description: "Hello World, I'm a Developer."
